In [ ]:
import numpy as np
import pandas as pd


In [ ]:
#Question 1

In [ ]:
#CREATING A VECTOR MANUALLY.
hor_vec=np.array((1,2,3,4,5))   # entering the array inputs and storing it in a variable hor_vec


In [ ]:
#Displaying the result
print(hor_vec)

[1 2 3 4 5]


In [ ]:
#CREATING THE VERTICAL VERTOR MANUALLY.
vert_vec=np.array(([1],[2],[3],[4],[5]))


In [ ]:
#Displaying vertical vector
print(vert_vec)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
#CREATING A ROW vector BY INPUT METHOD


elements_row = input("Enter the elements of the row vector separated by spaces: ").split()   # Geting input from the user for the vector elements
row_vector = np.array([float(element) for element in elements_row])                          # Converting the input elements to float and create a row vector
print("Row vector:", row_vector)                                                         # Printing the created row vector


Enter the elements of the row vector separated by spaces: 1 2 3 4 5 6 7 8 
Row vector: [1. 2. 3. 4. 5. 6. 7. 8.]


In [ ]:
#Creating a column vector by input

elements_column = input("Enter the elements of the column vector separated by spaces: ").split() # Getting input from the user for the vector elements
column_vector = np.array([float(element) for element in elements_column]).reshape(-1, 1)         # Converting the input elements to float and create a column vector
# Printing the created column vector
print("Column vector:")
print(column_vector)


Enter the elements of the column vector separated by spaces: 1 23 4 5 6 
Column vector:
[[ 1.]
 [23.]
 [ 4.]
 [ 5.]
 [ 6.]]


In [ ]:
#Question 2

In [ ]:
#CREATING A 5X5 MATRIX
#Manually
matrix=np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [2,5,6,7,8],
                [7,5,3,2,1]])

In [ ]:
#Displaying the matrix
matrix



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [ 2,  5,  6,  7,  8],
       [ 7,  5,  3,  2,  1]])

In [ ]:
matrix_1=matrix    #saving the matrix in a new variable so it can be further used.
matrix_2=matrix

In [ ]:
#CREATING THE MATRIX BY INPUT
Rows = int(input("Give the number of rows:"))   #taking input
Columns = int(input("Give the number of columns:"))
a = [[int(input()) for c in range (Columns)] for r in range(Rows)]
print(a)



Give the number of rows:5
Give the number of columns:5
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]


In [ ]:
#Displaying the martix
a = np.asarray(a)

a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#Question 3
thrd_row = a[2:3,:]    #selecting 3rd row and all columns.
thrd_row

array([[11, 12, 13, 14, 15]])

In [ ]:
#Question 4
forth_clo=a[:,3]  #Selecting all rows and 4th cloumn.
forth_clo.reshape(-1, 1)   #Displaying 4th coulumn

array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

In [ ]:
#QUESTION 5

In [ ]:
def sort_matrix_column_wise(matrix):     #creating a function.
    num_rows = len(matrix)
    num_cols = len(matrix[0])

    for col in range(num_cols):          #applying for loop.
        for i in range(num_rows - 1):
            for j in range(i + 1, num_rows):
                if matrix[j][col] < matrix[i][col]:
                    matrix[i][col], matrix[j][col] = matrix[j][col], matrix[i][col]


In [ ]:
sort_matrix_column_wise(matrix)

for row in matrix:
    print(row)

[1 1 2 2 3]
[2 3 4 5 5]
[5 6 6 7 8]
[ 7  7  8  9 10]
[11 12 13 14 15]


In [ ]:
#Sort element row wise
def sort_matrix_row_wise(matrix_1):
    num_rows = len(matrix_1)
    for i in range(num_rows):
        matrix_1[i].sort()

In [ ]:
sort_matrix_row_wise(matrix)
for row in matrix:
    print(row)

[1 1 2 2 3]
[2 3 4 5 5]
[5 6 6 7 8]
[ 7  7  8  9 10]
[11 12 13 14 15]


In [ ]:
#Question 6


b = np.empty_like(matrix)  # Initialize an empty matrix to store the modified values

# Applying the for loop to modify the matrix elements
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        if matrix[i, j] > 2:
            b[i, j] = matrix[i, j] * 10
        else:
            b[i, j] = matrix[i, j]

print("Original matrix:")
print(matrix)

print("\nModified matrix,b:")
print(b)








Original matrix:
[[ 1  1  2  2  3]
 [ 2  3  4  5  5]
 [ 5  6  6  7  8]
 [ 7  7  8  9 10]
 [11 12 13 14 15]]

Modified matrix,b:
[[  1   1   2   2  30]
 [  2  30  40  50  50]
 [ 50  60  60  70  80]
 [ 70  70  80  90 100]
 [110 120 130 140 150]]


In [ ]:
#Question 7

In [ ]:
matrix_sum = matrix + b
matrix_sum

array([[  2,   2,   4,   4,  33],
       [  4,  33,  44,  55,  55],
       [ 55,  66,  66,  77,  88],
       [ 77,  77,  88,  99, 110],
       [121, 132, 143, 154, 165]])

In [ ]:
#Question 8

In [ ]:
matrix_sub = b - matrix
matrix_sub

array([[  0,   0,   0,   0,  27],
       [  0,  27,  36,  45,  45],
       [ 45,  54,  54,  63,  72],
       [ 63,  63,  72,  81,  90],
       [ 99, 108, 117, 126, 135]])

In [ ]:
#Question 9

In [ ]:
element_wise_result = matrix * b
matrix_multiplication_result = np.dot(matrix,b)
element_wise_result


array([[   1,    1,    4,    4,   90],
       [   4,   90,  160,  250,  250],
       [ 250,  360,  360,  490,  640],
       [ 490,  490,  640,  810, 1000],
       [1210, 1440, 1690, 1960, 2250]])

In [ ]:
matrix_multiplication_result

array([[ 573,  651,  712,  792,  890],
       [1108, 1282, 1414, 1584, 1780],
       [1687, 1995, 2210, 2480, 2830],
       [2151, 2527, 2794, 3134, 3600],
       [3315, 3931, 4352, 4892, 5620]])

In [ ]:

#Question 10

In [ ]:
matrix_a_divided = matrix / 18
matrix_b_divided = b / 18




In [ ]:
matrix_a_divided

array([[0.05555556, 0.05555556, 0.11111111, 0.11111111, 0.16666667],
       [0.11111111, 0.16666667, 0.22222222, 0.27777778, 0.27777778],
       [0.27777778, 0.33333333, 0.33333333, 0.38888889, 0.44444444],
       [0.38888889, 0.38888889, 0.44444444, 0.5       , 0.55555556],
       [0.61111111, 0.66666667, 0.72222222, 0.77777778, 0.83333333]])

In [ ]:
matrix_b_divided

array([[0.05555556, 0.05555556, 0.11111111, 0.11111111, 1.66666667],
       [0.11111111, 1.66666667, 2.22222222, 2.77777778, 2.77777778],
       [2.77777778, 3.33333333, 3.33333333, 3.88888889, 4.44444444],
       [3.88888889, 3.88888889, 4.44444444, 5.        , 5.55555556],
       [6.11111111, 6.66666667, 7.22222222, 7.77777778, 8.33333333]])

In [ ]:

#Question 11

matrix_a_inverse = np.linalg.inv(matrix)
matrix_b_inverse = np.linalg.inv(b)
matrix_a_rank = np.linalg.matrix_rank(matrix)
matrix_b_rank = np.linalg.matrix_rank(b)
matrix_a_condition_number = np.linalg.cond(matrix)
matrix_b_condition_number = np.linalg.cond(b)
matrix_a_svd = np.linalg.svd(matrix)
matrix_b_svd = np.linalg.svd(b)
matrix_a_norm = np.linalg.norm(matrix)
matrix_b_norm = np.linalg.norm(b)

print("Matrix a Inverse:\n")
print(matrix_a_inverse)
print("Matrix B Inverse:\n")
print(matrix_b_inverse)
print("Matrix A Rank:\n", matrix_a_rank)
print("Matrix B Rank:\n", matrix_b_rank)
print("Matrix A Condition Number:\n", matrix_a_condition_number)
print("Matrix B Condition Number:\n", matrix_b_condition_number)
print("Matrix A Singular Value Decomposition:\n",matrix_a_svd)
print("Matrix B Singular Value Decomposition:\n",matrix_b_svd)
print("Matrix A Norm:\n", matrix_a_norm)
print("Matrix B Norm:\n", matrix_b_norm)

Matrix a Inverse:

[[-3.57142857e-01 -3.57142857e-01 -3.57142857e-01  1.00000000e+00
  -2.85714286e-01]
 [-1.42857143e-01 -1.42857143e-01  8.57142857e-01 -1.00000000e+00
   2.85714286e-01]
 [ 1.00000000e+00  2.22044605e-16 -1.00000000e+00 -1.00000000e+00
   1.00000000e+00]
 [-1.21428571e+00  7.85714286e-01 -2.14285714e-01  1.00000000e+00
  -5.71428571e-01]
 [ 6.42857143e-01 -3.57142857e-01  6.42857143e-01 -1.14194368e-15
  -2.85714286e-01]]
Matrix B Inverse:

[[-0.00982318 -0.02750491 -0.00098232  0.05049116 -0.02200393]
 [-0.00392927 -0.01100196  0.09960707 -0.11980354  0.03119843]
 [ 0.04518664  0.02652259 -0.19548134 -0.05225933  0.12121807]
 [-0.06876228  0.00746562  0.09312377  0.11343811 -0.1140275 ]
 [ 0.03536346 -0.00098232  0.00353635 -0.00176817 -0.00078585]]
Matrix A Rank:
 5
Matrix B Rank:
 5
Matrix A Condition Number:
 105.60968977307618
Matrix B Condition Number:
 116.61344658721416
Matrix A Singular Value Decomposition:
 (array([[-0.10842565, -0.53107617,  0.60928488, -0

In [ ]:
#QUESTION 12.
column_vector_norm = np.linalg.norm(column_vector)
column_vector_inner_product = np.inner(column_vector.flatten(), column_vector.flatten())
column_vector_outer_product = np.outer(column_vector, column_vector)

In [ ]:
column_vector_inner_product


91.0

In [ ]:
column_vector_outer_product

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 2.,  4.,  6.,  8., 10., 12.],
       [ 3.,  6.,  9., 12., 15., 18.],
       [ 4.,  8., 12., 16., 20., 24.],
       [ 5., 10., 15., 20., 25., 30.],
       [ 6., 12., 18., 24., 30., 36.]])

In [ ]:
#Question 13
def derivative(f, a, method='central', h=0.01):
    if method == 'forward':
        return (f(a + h) - f(a)) / h
    elif method == 'backward':
        return (f(a) - f(a - h)) / h
    elif method == 'central':
        return (f(a + h) - f(a - h)) / (2 * h)
    else:
        raise ValueError("Invalid method. Choose 'forward', 'backward', or 'central'.")

In [ ]:
x = 1

derivative_f1 = derivative(np.exp, x)
derivative_f2 = derivative(np.cos, x)

print("Derivative of exp(x) at x = 1:", derivative_f1)
print("Derivative of cos(x) at x = 1:", derivative_f2)

Derivative of exp(x) at x = 1: 2.718327133382714
Derivative of cos(x) at x = 1: -0.8414569603616029


In [ ]:
#Question 14
excel_file_path = '/content/AWS.xlsx'
df = pd.read_excel(excel_file_path) # Reading the Excel file into a DataFrame
print(df.head()) # Displaying the first few rows of the DataFrame

                  created_at  entry_id  Soil Temperature  Soil Moisture  \
0  2022-12-14T14:19:11+05:30     10830             21.06            817   
1  2022-12-14T14:20:13+05:30     10831             21.06            817   
2  2022-12-14T14:21:15+05:30     10832             21.06            817   
3  2022-12-14T14:22:18+05:30     10833             21.06            817   
4  2022-12-14T14:23:20+05:30     10834             21.06            817   

   Wind Speed  Rainfall  Temperature  Humidity  Pressure  Battery Voltage  
0         0.0      0.25        25.38     45.09      1.94             4.14  
1         0.0      0.25        25.27     46.52      1.94             4.14  
2         0.0      0.25        25.34     45.79      1.94             4.14  
3         0.0      0.25        25.13     44.91      1.94             4.15  
4         0.0      0.25        24.95     45.12      1.94             4.15  
